spring:
  data:
    mongodb:
      uri: mongodb+srv://User:loveyadav@cluster0.kp1wyhg.mongodb.net/journaldb?retryWrites=true&w=majority
      auto-index-creation: true
      database: journaldb

server:
  port: 8081
  servlet:
    context-path: /journal
