spring:
  redis:
    host: redis://default:OiehS6a5FuKCVrTulhQsO6nZEmUDx96z@redis-13604.c305.ap-south-1-1.ec2.cloud.redislabs.com:13604
    port: 13604
    password: OiehS6a5FuKCVrTulhQsO6nZEmUDx96z
  data:
    mongodb:
      uri: mongodb+srv://User:loveyadav@cluster0.kp1wyhg.mongodb.net/journaldb?retryWrites=true&w=majority
      auto-index-creation: true
      database: journaldb
  mail:
    host: smtp.gmail.com
    port: 587
    userName: loveyadavrajakataal@gmail.com
    password: mkoefejbsixsozxs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.Origin.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='XUS4S5RP4LGSY3JB' password='cfltlB9wihQF0vSa1767FHOWtrpCYxtIAKk4uczdM3PXCzeBpkWrKvfEi7t/P57w';
      session:
        timeout:
          ms: 45000

server:
  port: 8080

weather:
  api:
    key: e52982e870df3182e0c54f014771c766